// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package sqlite

import (
	"database/sql"
)

type Assignment struct {
	ID         int64         `json:"id"`
	CourseID   int64         `json:"course_id"`
	Name       string        `json:"name"`
	DueDate    sql.NullTime  `json:"due_date"`
	CreatedAt  sql.NullTime  `json:"created_at"`
	Difficulty sql.NullInt64 `json:"difficulty"`
	Length     sql.NullInt64 `json:"length"`
}

type Course struct {
	ID        int64        `json:"id"`
	Name      string       `json:"name"`
	CreatedAt sql.NullTime `json:"created_at"`
}
