// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package psql

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Assignment struct {
	ID        int32              `json:"id"`
	CourseID  int32              `json:"course_id"`
	Name      string             `json:"name"`
	DueDate   pgtype.Timestamptz `json:"due_date"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type Course struct {
	ID        int32              `json:"id"`
	Name      string             `json:"name"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}
